### ISSUE TITLE
示例中的GIF动画是怎么做的？

### ISSUE THREAD

**Issue by panpf** [ryanhoo/Zhihu-Parallax-Animation#2]
您好，请教一下您示例中的GIF动画是怎么做出来的，我现在是用studio录制一段视频，然后用视频转GIF的工具转成GIF图片，可是效果很差劲，我看您的效果很好

**Comment by ryanhoo** [comment]
我用的 **LICEcap** ，录制的图片清晰而且体积不大，不过是 mac 上的，如果是 windows 上也有 gif 屏幕录制软件的，我以前用过，你自己去搜搜。
